### ISSUE TITLE
Vim mode

### ISSUE THREAD

**Issue by santiyounger** [ryanpcmcquen/obsidian-org-mode#1]
Hey,

Thank you so much for making this plugin. I've had so many .org files. It was so frustrating to not be able to open them in Obsidian so thank you for this.

I'd love to request  for  vim key bindings to work with this plugin

![image](https://user-images.githubusercontent.com/51902730/118193069-c6a15080-b40c-11eb-9be4-ef87511757a9.png)

I have vim activated (as seen in the screenshot above) however when I open an `.org` file vim mode stops working.

I'm a heavy user of evil mode / spacemacs, which is why I really depend on vim mode for writing.

Thank you so much

**Comment by ryanpcmcquen** [comment]
Should just be a matter of reading the settings and binding the keymap to that.

**Comment by santiyounger** [comment]
thanks for the quick response, is this something that could already be done from the users side? Or did I misunderstand what you meant? Thanks!

**Comment by ryanpcmcquen** [comment]
No, this would be a code change.

**Comment by santiyounger** [comment]
Perfect got you, super excited for the development of this plugin, thank you so much for your efforts

**Comment by ryanpcmcquen** [comment]
Landed in [1.2.0](https://github.com/ryanpcmcquen/obsidian-org-mode/releases/tag/1.2.0). A future improvement would be to get the actual user `keyMap`, instead of just checking `app.vault.config.vimMode`, but for now this is an improvement.

**Comment by santiyounger** [comment]
that's amazing thank you so much for your work. It works great on my side
