### ISSUE TITLE
Support .org_archive files

### ISSUE THREAD

**Issue by jonmseaman** [ryanpcmcquen/obsidian-org-mode#11]
If you archive a note in Emacs Org mode, it is normally moved to a file with same name, but with an org_archive extension.
Is it possible to get support added for org_archive files?

**Comment by ryanpcmcquen** [comment]
@jonmseaman is an `org_archive` file just an Org Mode file with a different extension? I'm not familiar with them.

**Comment by ryanpcmcquen** [comment]
Should work here:
https://github.com/ryanpcmcquen/obsidian-org-mode/releases/tag/1.4.0
