### ISSUE TITLE
Confused about how to enable the org mode in the notes

### ISSUE THREAD

**Issue by ababkin** [ryanpcmcquen/obsidian-org-mode#12]
Hi, I'm new to Obsidian.
I've installed and enabled the org-mode plugin
Then i try to create a note, but it's the vanilla MD and the outlines don't work.
I understand I need to do something to enable the outlining/collapsing but have no idea how to do that.
I could not find any documentation
Please help
Thanks

**Comment by ryanpcmcquen** [comment]
You have to manually create a `.org` file outside of Obsidian and put it in your Vault.
