### ISSUE TITLE
logseq support?

### ISSUE THREAD

**Issue by huyz** [ryanpcmcquen/obsidian-org-mode#8]
Maybe this could be a separate plugin, but logseq is getting popular and many people like to use both [logseq and obsidian together](https://discuss.logseq.com/t/logseq-and-obsidian-md-colaboration-projects/473).

I've started using logseq and have opted to use the `markdown` file format as source and would be interested to see if I can still view the files in Obsidian.

In order for the plugin to know which markdown files to parse, maybe a page property could be set to signify this is a logseq file or maybe only markdown files under configured paths?

**Comment by ryanpcmcquen** [comment]
That sounds like a separate product.
