### ISSUE TITLE
Doc Request: Please explain what "Org Mode" is

### ISSUE THREAD

**Issue by brandonzylstra** [ryanpcmcquen/obsidian-org-mode#9]
No where in your README do I see any explanation as to what "Org Mode" is.  It would be helpful to explain this or link to some existing explanation.

**Comment by ryanpcmcquen** [comment]
Good callout, any suggestions beyond the main site?

https://orgmode.org/

**Comment by brandonzylstra** [comment]
ahhhh, very cool... this looks really useful!   It looks like it does what Markdown _should have done_.

**Comment by ryanpcmcquen** [comment]
Yes, it's quite powerful, especially inside Emacs!
